/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerVenda;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifnsilva
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
        
    }
    public Venda(String id) throws SQLException{
        initComponents();
        controller = new ControllerVenda(this);
        controller.printCotacao();
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ControllerVenda getController() {
        return controller;
    }

    public void setController(ControllerVenda controller) {
        this.controller = controller;
    }

    public JButton getBtBitcoin() {
        return btBitcoin;
    }

    public void setBtBitcoin(JButton btBitcoin) {
        this.btBitcoin = btBitcoin;
    }

    public JButton getBtEthereum() {
        return btEthereum;
    }

    public void setBtEthereum(JButton btEthereum) {
        this.btEthereum = btEthereum;
    }

    public JButton getBtRipple() {
        return btRipple;
    }

    public void setBtRipple(JButton btRipple) {
        this.btRipple = btRipple;
    }

    public JButton getBtVolta() {
        return btVolta;
    }

    public void setBtVolta(JButton btVolta) {
        this.btVolta = btVolta;
    }

    public JLabel getLblBitcoin() {
        return lblBitcoin;
    }

    public void setLblBitcoin(JLabel lblBitcoin) {
        this.lblBitcoin = lblBitcoin;
    }

    public JLabel getLblEthereum() {
        return lblEthereum;
    }

    public void setLblEthereum(JLabel lblEthereum) {
        this.lblEthereum = lblEthereum;
    }

    public JLabel getLblRipple() {
        return lblRipple;
    }

    public void setLblRipple(JLabel lblRipple) {
        this.lblRipple = lblRipple;
    }

    public JTextField getTxtBitcoin() {
        return txtBitcoin;
    }

    public void setTxtBitcoin(JTextField txtBitcoin) {
        this.txtBitcoin = txtBitcoin;
    }

    public JTextField getTxtEthereum() {
        return txtEthereum;
    }

    public void setTxtEthereum(JTextField txtEthereum) {
        this.txtEthereum = txtEthereum;
    }

    public JTextField getTxtRipple() {
        return txtRipple;
    }

    public void setTxtRipple(JTextField txtRipple) {
        this.txtRipple = txtRipple;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btBitcoin = new javax.swing.JButton();
        btRipple = new javax.swing.JButton();
        btEthereum = new javax.swing.JButton();
        lblBitcoin = new javax.swing.JLabel();
        lblRipple = new javax.swing.JLabel();
        lblEthereum = new javax.swing.JLabel();
        btVolta = new javax.swing.JButton();
        txtBitcoin = new javax.swing.JTextField();
        txtRipple = new javax.swing.JTextField();
        txtEthereum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btBitcoin.setText("Vender Bitcoin");
        btBitcoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBitcoinActionPerformed(evt);
            }
        });

        btRipple.setText("Vender Ripple");
        btRipple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRippleActionPerformed(evt);
            }
        });

        btEthereum.setText("Vender Ethereum");
        btEthereum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEthereumActionPerformed(evt);
            }
        });

        lblBitcoin.setText("Bitcoin: ");

        lblRipple.setText("Ripple: ");

        lblEthereum.setText("Ethereum: ");

        btVolta.setText("Voltar para o menu");
        btVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBitcoin)
                    .addComponent(lblRipple)
                    .addComponent(lblEthereum))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEthereum, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(btEthereum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRipple, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRipple)
                            .addComponent(btBitcoin))))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btVolta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBitcoin)
                    .addComponent(lblBitcoin)
                    .addComponent(txtBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRipple)
                    .addComponent(lblRipple)
                    .addComponent(txtRipple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEthereum)
                    .addComponent(lblEthereum)
                    .addComponent(txtEthereum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btVolta)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>                        

    private void btVoltaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.setVisible(false);
        Menu m = new Menu(id);
        m.setVisible(true);
    }                                       

    private void btBitcoinActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            controller.atualizar(id,1,0,0);
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void btRippleActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            controller.atualizar(id,0,1,0);
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void btEthereumActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        try {
            controller.atualizar(id,0,0,1);
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Venda().setVisible(true);
//            }
//        });
//    }
    private String id;
    private ControllerVenda controller;
    // Variables declaration - do not modify                     
    private javax.swing.JButton btBitcoin;
    private javax.swing.JButton btEthereum;
    private javax.swing.JButton btRipple;
    private javax.swing.JButton btVolta;
    private javax.swing.JLabel lblBitcoin;
    private javax.swing.JLabel lblEthereum;
    private javax.swing.JLabel lblRipple;
    private javax.swing.JTextField txtBitcoin;
    private javax.swing.JTextField txtEthereum;
    private javax.swing.JTextField txtRipple;
    // End of variables declaration                   
}
